import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'


import Currency from './Currency/Currency'
const inter = Inter({ subsets: ['latin'] })
import Time from './Time/Time'
export default function Home() {

  return (
    <>
      <Head>
        <title>Any Currency Converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>

          <Currency />
          <Time />
        </div>


      </main>
    </>
  )
}
